// <auto-generated />
using System;
using EduvisualWebApp.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EduvisualWebApp.Migrations
{
    [DbContext(typeof(EduvisualContext))]
    [Migration("20210402143924_TesteMigration")]
    partial class TesteMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.4");

            modelBuilder.Entity("EduvisualDomain.Models.Equipamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("NomeEquipamento")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ValorEquipamento")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Equipamentos");
                });

            modelBuilder.Entity("EduvisualDomain.Models.Funcionario", b =>
                {
                    b.Property<int>("IdFuncionario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataDeCadastro")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Metrial")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .HasColumnType("TEXT");

                    b.HasKey("IdFuncionario");

                    b.ToTable("Funcionarios");
                });

            modelBuilder.Entity("EduvisualDomain.Models.ReservaEquipamento", b =>
                {
                    b.Property<int>("IdReserva")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataDevolucao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataReserva")
                        .HasColumnType("TEXT");

                    b.Property<int?>("EquipamentoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NomeFuncionario")
                        .HasColumnType("TEXT");

                    b.Property<int>("QuantidadeEquipamento")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("StatusReserva")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdReserva");

                    b.HasIndex("EquipamentoId");

                    b.ToTable("ReservaEquipamentos");
                });

            modelBuilder.Entity("EduvisualDomain.Models.ReservaEquipamento", b =>
                {
                    b.HasOne("EduvisualDomain.Models.Equipamento", "Equipamento")
                        .WithMany()
                        .HasForeignKey("EquipamentoId");

                    b.Navigation("Equipamento");
                });
#pragma warning restore 612, 618
        }
    }
}
